- name: create restic config dir
  become: true
  file:
    state: directory
    path: "{{ restic_paths_config_folder }}"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"

- name: Create restic config file
  become: true
  template:
    src: restic.env.j2
    dest: "{{ restic_paths_config_file }}"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: 0700

- name: Save restic password to file
  become: true
  copy:
    content: "{{ restic_conf_password }}"
    dest: "{{ restic_conf_password_file }}"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: 0700
  no_log: true
  when: restic_conf_password_file and restic_conf_password
