- name: Install restic
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name: restic
    state: latest

- name: Self-upgrade restic
  become: true
  ansible.builtin.command: restic self-update
  when: restic_self_upgrade
